### ISSUE TITLE
Update 'Getting Started' with devise instructions

### ISSUE THREAD

**Issue by jeanruggiero** [ForestJay/EmpEmp#17]
As a developer
I want to clone, install, and run EmpEmp using the 'Getting Started' instructions in the README
Such that I can contribute to the project

Given that I have followed all prior instructions in the README
When I run `rails db:migrate`
Then the database should migrate successfully

After following the instructions in the README and running `rails db:migrate`, I got the following error: 
```
rails aborted!
NoMethodError: undefined method `devise' for User (call 'User.connection' to establish a connection):Class
```

Following [these instructions](https://stackoverflow.com/a/33633802), I renamed config/initializers/devise.rb.dummy to devise.rb. This caused `rails db:migrate` to run successfully, however running `rails test` results in several errors which seem to indicate a failed migration:
```
ActiveRecord::StatementInvalid: Could not find table 'users'
```

**Comment by ForestJay** [comment]
Thanks for reporting this @jeanruggiero . I might have trouble reproducing this on my computer, maybe I can spin up a VM or I can walk you through some options to fix it.

**Comment by ForestJay** [comment]
I think I've reproduced this. I'm going to try to resolve ASAP. Thanks again @jeanruggiero . :)

**Comment by ForestJay** [comment]
It seems likely that this was introduced by the groundwork from Issue #14 .

**Comment by ForestJay** [comment]
It looks like deleting the `devise_for :users` from config/routes.rb allows `rails generate devise:install` to succeed. It's a kludge though, perhaps the database migration is more important than I had realized.

**Comment by ForestJay** [comment]
Hi @jeanruggiero , I think the changes I just merged to master have fixed it. I'm not sure if just doing a pull and going through the instructions will fix the working directory you have. It might be best to test in a brand new checkout of master. I'm a little worried my changed to the README are confusing. I'll leave this issue open for a few days in case you have times to test. Thanks again for finding this!

**Comment by jeanruggiero** [comment]
@ForestJay, I pulled your latest changes and followed the new instructions in the README and it works! Thanks for adding the part about how to run the server - that was going to be my next Google escapade.
